### ISSUE TITLE
Upgrades that give ships extra upgrade slots aren't giving the ships extra slots in the tournament listing.

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#77] opened 2018-03-01 18:15 UTC
By extension. Lists with more upgrade slots than usual don't get the extra upgrades in matches.

**Comment by Sleet01** [comment] 2018-03-01 18:28
Can you give an example squad as displayed in the squad #1 or squad#2 box?  If possible, with the date and country of origin as well? I'd like to compare the tournament data to the internal representation.

**Comment by boredompwndu** [comment] 2018-03-01 18:34
![image](https://user-images.githubusercontent.com/8730661/36862517-08742232-1d55-11e8-9996-9f4af8eaa94b.png)


Is this what you are looking for?

The squad appears to be from Sweden

**Comment by Sleet01** [comment] 2018-03-01 18:41
Perfect!  I'm guessing the problem is not extra slot upgrades per se, but unimplemented extra slot upgrades that XWS-bench currently doesn't know how to convert to a text string representation.  With this data I can track down the exact tournament list and verify that we are using correct conversions (xws-spec [https://github.com/elistevens/xws-spec/blob/master/README_NAMES.md] being the gold standard)and see whether all cards in this specific list are implemented yet.  Thanks!

**Comment by boredompwndu** [comment] 2018-03-01 18:42
Cool. Other common troublemakers include starviper mk2, vaksai, and smuggling compartment

**Comment by boredompwndu** [comment] 2018-03-01 18:46
Starviper mk2, vaksai, and smuggling compartment lists

![image](https://user-images.githubusercontent.com/8730661/36863127-d21c5ff4-1d56-11e8-8e35-92b6c77359f0.png)


Both from 2-24-18 from sweden

**Comment by Sleet01** [comment] 2018-03-01 20:01
Offending tourney appears to be 4092, initial instance is this list:

`{
        "list": {
          "faction": "scum",
          "pilots": [
            {
              "name": "fennrau",
              "ship": "protectoratestarfighter",
              "upgrades": {
                "ept": [
                  "attannimindlink"
                ],
                "mod": [
                  "autothrusters"
                ],
                "title": [
                  "concorddawnprotector"
                ]
              }
            },
            {
              "name": "thweek",
              "ship": "starviper",
              "upgrades": {
                "illicit": [
                  "glitterstim"
                ],
                "mod": [
                  "autothrusters"
                ],
                "system": [
                  "firecontrolsystem"
                ],
                "title": [
                  "starvipermkii",
                  "virago"
                ]
              }
            },
            {
              "name": "talonbanecobra",
              "ship": "kihraxzfighter",
              "upgrades": {
                "ept": [
                  "attannimindlink"
                ],
                "illicit": [
                  "contrabandcybernetics"
		],
                "mod": [
                  "engineupgrade",
                  "vectoredthrusters",
                  "autothrusters"
                ],
                "title": [
                  "vaksai"
                ]
              }
            }
          ],
          "vendor": {
            "listjuggler": {}
          },
          "version": "4.2.0"
        },
        "mov": 461,
        "name": "Andreas Norman",
        "rank": {
          "swiss": 6
        },
        "score": 2,
        "sos": "0.44"
}`

I was able to build the list correctly (although replacing Contraband Cybernetics with another instance Glitterstim) but upon return to the squad selection screen the squad point value is now wrong.  

Thweek + Autothrusters + StarViper Mk. II + Virago + Glitterstim + Fire-Control System
Talonbane Cobra + Attanni Mindlink + Glitterstim + Engine Upgrade + Vaksai + Vectored Thrusters + Autothrusters
Fenn Rau + Attanni Mindlink + Autothrusters + Concord Dawn Protector
(Create-time cost: 98pts.  Display-time cost: 100pts.)


This points to a couple of issues:

1) Lack of intelligence in either teams.js' tosquadron() or parsejuggler() regarding slot dependencies

2) Lack of intelligence in calculating costs

**Comment by Sleet01** [comment] 2018-03-01 20:36
Addendum: the V2 List Juggler API's JSON files contain points costs for each squad and upgrade, but at this point they do not look correct.

**Comment by Sleet01** [comment] 2018-03-01 21:08
Further addendum: initial loading issue appears to be in team.js' parseJSON() function.  Other mentioned functions do no checks on listed upgrades vs. a ship or pilot's "allowed" upgrades.  I would not be surprised if it were possible to build a list in XWS-bench that could not be *loaded* in XWS-bench right now.

**Comment by Sleet01** [comment] 2018-03-04 22:24
This is going to require a complete rewrite of the list-handling code, because A) we're basically doing three different parse calls every time a list is loaded, displayed, or edited; and B) the old List Juggler spec doesn't handle egregious ambiguous lists like:

`Captain Nym + Push the Limit + Twin Laser Turret + Extra Munitions + Harpoon Missiles + Bomblet Generator + Engine Upgrade + Havoc + Trajectory Simulator + R4-E1
Sabine Wren + Engine Upgrade`

which could be either Rebel or Scum.

Sozin on the FFG forums was kind enough to update the List Juggler pretty-print spec, so we can move forward with more intelligent raw text importing (like on the list selection page where we allow players to paste in human-readable lists) but the internal representation and repeated re-parsing needs to be scrapped.

It's a little heavyweight, but my proposal would be to internally represent all lists as a new object type that includes a JSON string, a human-readable string, and some conversion methods.  Currently this code all lives in the Team object and we end up passing strings around about a thousand times a second.

**Comment by Sleet01** [comment] 2018-04-17 21:49
This should be fixed in the Parsing pull request.

**Comment by boredompwndu** [comment] 2018-04-18 03:56
Fantastic

**Comment by Sleet01** [comment] 2018-05-08 06:26
Parsing updates are now live in Release.  I took a laissez-faire approach: if a list comes in from a tournament, a previous saved list, a valid JSON text pasted in, or a valid List Juggler human-readable list pasted in, we assume it is valid and then calculate the point values accordingly.  We now only enforce slot usage rules within the Create page.

I went with this approach for a few reasons: 

1. enforcing slot counts during import/export requires a lot of extra effort and really doesn't matter most of the time.  By contrast, applying point cost bonuses is a walk in the park.
2. once a list is saved as JSON it should have already been validated somewhere else - within our Create page, by tournament organizers, in whatever app it was copied from - so we can reasonably assume that a saved list is valid.  But since point values are not usually saved in either of the standard formats, we would have to recalculate point costs anyhow.
3. A squadron list that is on the game board doesn't need to have any conception of slot counts.  Full slots are represented by the upgrade instances in play; empty slots are meaningless to the rule set and are thus completely ignored.

So now lists created *in* XWS-bench are validated at build time, but no validation of slot counts occurs on saved lists.

Closing for now; please file new issues against parsing if new issues are encountered.

**Closed as completed by Sleet01** 2018-05-08 06:26 UTC
