### ISSUE TITLE
#Advanced Sensor + PTL

### ISSUE THREAD

**Issue by simonvogel** [baranidlo/bench#55] opened 2018-02-18 19:14 UTC
I like to play Control brobots and until the recent update it worked pretty well with PTL+AS. However, in v0.99.8 things changed. I can only use PTL+AS on one of the ships, the next one is not automatically selected and can therefore not use Advanced Sensors. I don't know why this has changed. :/

**Comment by Sleet01** [comment] 2018-02-18 19:33
Please post your full list and I will check it out.

**Comment by Sleet01** [comment] 2018-02-19 18:29
This was actually caused by my Snap Shot fix code, but I've backed out the problematic code and updated Snap Shot to act more like Adaptive Ailerons (essentially doubling the end-of-activation notifications).

As an aside, have you noticed any issues with e.g. IG-88B + IG-2000 granting *2* additional cannon shots, rather than just one, prior to the most recent update?

**Comment by simonvogel** [comment] 2018-02-19 20:04
The additional 2 cannon shots is new aswell. It didn't occur before.

**Comment by Sleet01** [comment] 2018-02-19 20:48
Yeah, that was my work as well.  I put in another hotfix which should put everything back the way it was, but leave Snap Shot working as well.  Sorry for the trouble.

**Comment by Sleet01** [comment] 2018-02-20 20:07
Should all be working correctly in the release code now.

**Comment by Sleet01** [comment] 2018-05-02 16:28
No new issues since last update; closing.

**Closed as completed by Sleet01** 2018-05-02 16:28 UTC
