### ISSUE TITLE
r4 agromech softlocks the game.

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#7] opened 2017-12-28 03:50 UTC
when an ai controlled ship has the r4 agromech equipped, if it rolls focus results while it has a focus token, it will not actually fire. instead the red dice appear to have been rolled, but the attack is not completed

**Comment by boredompwndu** [comment] 2017-12-28 03:51
the best testing scenario is shoving 5 y-wings with r4 agromech against eachother and letting the ai run both sides

**Comment by Sleet01** [comment] 2017-12-30 09:32
Caused by an infinite loop in the roll modification step, somehow.  Checking...

**Comment by Sleet01** [comment] 2018-01-06 00:36
Preliminary fix is in the latest Pull Request.

Root cause: the custom code for R4 did not check to see if it was already executing itself during the subsequent re-check of dice modifiers.  This led to an infinite recursion.  I added a guard flag and removed what looks like an extraneous call to re-calculate all dice; this appears to work correctly (if rather naively).

**Comment by Sleet01** [comment] 2018-01-06 15:11
Changed the fix to exclude AI pilots from calling the dice results display function, as they use a different version and the combo is what caused the infinite recursion.  The "extraneous" calls were put back in, though, as they are necessary for human players to use R4.

**Comment by baranidlo** [comment] 2018-01-13 17:07
Should be fixed in v0.99.5.

**Closed as completed by baranidlo** 2018-01-13 17:07 UTC
