### ISSUE TITLE
The chosen maneuver on my ship can randomly change

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#71] opened 2018-02-27 15:17 UTC
This is hard to explain. A ship I had planned a 4k with during the planning phase had its dial change to a 3 bank right. This had happened to me a couple times before and wrote it off as player error. This time I saw the selected maneuver change

**Comment by Sleet01** [comment] 2018-02-27 17:09
I think this is a problem with Criticals that reduce your dial options: Shaken Pilot, maybe one or two more.  Was one of these crits in play at the time?  If not, there may be a more general issue, or some pilot ability may be the cause.

**Comment by boredompwndu** [comment] 2018-02-28 04:07
Not that I was aware of. I'll keep a better eye on dialspinning

**Comment by boredompwndu** [comment] 2018-03-03 14:43
![image](https://user-images.githubusercontent.com/8730661/36935545-20e2970e-1ec7-11e8-9446-32a09630aaa4.png)

In this scenario, I had received a shaken pilot crit in the previous turn. I had dialed in a 3 hard right. The other ships activated.  When I became the active ship (selected, etc) my dial was changed to a 3 bank left

**Comment by boredompwndu** [comment] 2018-03-15 18:01
As a followup. dialspinning seems to be occurring specifically around the shaken pilot crit. I haven't isolated the details of what causes it, but it is happening for both AI ships 
(found through intel agent) and player ships. The dial can change to straight maneuvers somehow as well

**Comment by Sleet01** [comment] 2018-04-21 22:31
Congratulations!  You have been chosen as the 1,000th bug!  You are now the proud owner of: getting fixed!  While I'm waiting for feedback on my RFC, I'll take a look at this.

**Comment by Sleet01** [comment] 2018-04-22 03:01
Should be fixed in the latest PR, at least for Shaken Pilot crits.  I'll see if I can track down any other paths.

**Comment by Sleet01** [comment] 2018-05-08 17:42
This should be fixed in Release.  If you see any other issues with changing dials, please file a new issue!  Closing.

**Closed as completed by Sleet01** 2018-05-08 17:42 UTC
