### ISSUE TITLE
Everyone is Fel's wrath now

### ISSUE THREAD

**Issue by Iskalonian** [baranidlo/bench#45] opened 2018-02-05 09:49 UTC
Hi, thank you for updating and maintaining this. Great work, I just gave you a small donation. It seems like  destroyed ships does not get removed before the end of the round and not at the end of their initiative phase.

**Comment by Sleet01** [comment] 2018-02-05 09:52
Hi, thanks!  Can you provide the exact lists you used when you found the issue?  Thanks!

**Comment by Iskalonian** [comment] 2018-02-05 11:21
It did seem like the one Rho I lost was removed after it had no hull left,
but all of the Scurrgs was there until the end, doing their shooting.

Maarek Stele + Lone Wolf + TIE/x7
Rho Squadron Veteran + Harpoon Missiles + Push the Limit + Advanced SLAM + Os-1
Arsenal Loadout
Rho Squadron Veteran + Harpoon Missiles + Push the Limit + Advanced SLAM +
Os-1 Arsenal Loadout

vs

Karthakk Pirate + Ion Cannon Turret + Harpoon Missiles + Long-Range Scanners
Lok Revenant + Deadeye + Extra Munitions + Harpoon Missiles + Guidance Chips
Lok Revenant + Deadeye + Extra Munitions + Harpoon Missiles + Boba Fett +
Guidance Chips

**Comment by Sleet01** [comment] 2018-02-07 09:39
I'm pretty sure this is a Harpoon missile issue but not sure yet.  This is next on my list so I hope to have a fix in tomorrow.

**Comment by Sleet01** [comment] 2018-02-07 18:51
My testing is showing ships being removed and destroyed correctly, even with Harpooned! in place.  There may be an issue with dual Harpooned! as I did get one "zombie" ship in the first test run, but I'm not sure that's the root cause.  Will keep looking.

**Comment by Sleet01** [comment] 2018-02-07 19:32
As a further aside... both of these lists are exceedingly nasty.

**Comment by Iskalonian** [comment] 2018-02-08 06:38
They truly are. I am trying out to see which ship I should pair with the
RHOs. PTL, title and Adv SLAM gives them the possibility to launch Harpoons
every round. You can even have 3 of them with Thread Tracers to counter
Countermeasures and Poe. Lone Wolf is not so good in 3 ship builds.

I really appreciate the work you put in.

B/r
Mikkel

7. feb. 2018 20:32 skrev "Sleet01" <notifications@github.com>:

**Comment by Sleet01** [comment] 2018-02-08 21:45
Okay, I think I may have a repro.  Did you notice this specifically when dealing crits as the very last attack of a turn?  

Between Harpoon Missiles, Maarek Stele, Guidance Chips, and Boba Fett, there are a lot of crits flying around.  It appears, although I need to confirm this, that some part of this combo is either preventing the final death check after resolving crits or allowing the next phase to start without death checks.  I think the easiest fix would be to run checkdead() on every ship at the top of every phase, but the cleanest fix would be to find the offending upgrade card and fix *it*.

I'll update when I have a working fix.

**Comment by Iskalonian** [comment] 2018-02-09 12:35
Tried another list with Vader and the two PTL OS-1 RHOs, seems like the
OS-1 title is not functioning properly. I can not shot missilies. It was
against the Tournament list with Fenn and two Kimoglias.

**Comment by Sleet01** [comment] 2018-02-09 21:24
I'm not having any issues with this matchup in the current release version.  OS-1 worked fine, Advanced SLAM worked fine; the main issue was the Cartel Executioners having initiative over the Rho Squadron Vets.  I didn't see any exceptions from the code or failed attacks, so this may be a transient.  

The current gh-pages OS-1 / XG-1 code is up to date with the devel codebase, so these should be working correctly.  I did notice some weirdness when loading the Vader + Rhos list for editing; there's an update to the list-loading code on the way but for now an edited list may behave badly when put into the game.  The simplest work-around is to make a list from scratch if you need to change it.

Please do continue to update if you see more issues; if possible, please include a screen shot or copy of the debugging console (\<ctrl\>+\<shift\>+\<i\> in Chrome and Firefox; \<F12\>, \<ctrl\>+\<2\> in IE, \<⌥\>+\<⌘\>+\<c\> in Safari) as well.  Thanks!

**Comment by Iskalonian** [comment] 2018-02-19 08:30
Hi,

When I try this Imperial list, 2 things happen. The reinforce actions (fore
& aft) is transfered to my ships when, so I have 3 options; move, fore and
aft. I can then chose which section of the AI ship reinforces, I can do
that and press move and everything continues. I can also not chose fore or
aft, but then they do not get the reinforce token, and I am only able to
that on one of hte 2 ships that move simultainesly.

Then when I do the cloak action with Whisper there is no way to go forward.
I am not able to press "Next". This also happens when I chose other actions
than cloak.

Rho Squadron Veteran + Push the Limit + Harpoon Missiles + Advanced SLAM +
Os-1 Arsenal Loadout
Rho Squadron Veteran + Deadeye + Harpoon Missiles + Guidance Chips
Whisper + Veteran Instincts + Fire-Control System + Agent Kallus + Advanced
Cloaking Device

vs

Wookiee Liberator + Expertise + Tactician + Guidance Chips
Wookiee Liberator + Expertise + Tactician + Guidance Chips
Lowhhrick + Predator + Tactician + C-3PO + Guidance Chips

**Comment by Sleet01** [comment] 2018-02-19 19:00
Hey, @Iskalonian ,

I pretty much broke most special actions while working on Snap Shot.  Currently a lot of stuff is not working.  I apologize, but could you check this stuff again after we pull the hotfix for my snafu into the release branch?  Not sure what the timeframe is yet but it should be fairly soon.

Thanks!

**Comment by Iskalonian** [comment] 2018-02-20 07:57
Just tried, still not able to proceed past the first turn

**Comment by Sleet01** [comment] 2018-02-20 19:45
It's working on devel code, so the last few hotfix updates will bring it back in line.  Again, that's my bad - I broke almost all out-of-activation actions while working on Snap Shot.  It should all be working correctly when the latest Pull Request is merged with the /devel and /gh-pages branches.

Edit: last hotfixes are in; looks like the above two lists are working correctly on release code.  Also: are Auzitucks completely degenerate, or is it just a problem for Imps?

**Comment by Iskalonian** [comment] 2018-02-27 14:48
Some weird things are happening.

After I do a SLAM the first round with the Gunboat, the following rounds I
am not able to do any actions.
Heavy Laser Cannon into Dengar, I choose to use Crack Shot and reroll from
Linked Battery. Dengar is obviously cheating :)
One other note, I get the option to activate Crack Shot when the ship with
Crack Shot is being shot at.

[image: Inline image 1]

**Comment by Sleet01** [comment] 2018-03-06 07:29
I think I found the smoking gun re: ships not dying after critical damage is applied.  The applydamage() code and applycritical() code is 100% identical *except* that applycritical() does not do a check for death after applying the criticals' special rules.  Presumably this is so that some abilities that proc on faceup cards have a chance to fire.  I'll add a new end-of-attack check for death which should work no matter what.

**Comment by Sleet01** [comment] 2018-05-02 16:25
The post-critical-death stuff should be working, but I'd like to add a check for death at the end of every round as well, just to be sure.  I'll see if I can get that in before this weekend.

**Comment by Sleet01** [comment] 2018-05-08 19:50
I cannot get this in before this weekend :)  I'll add it before the next update, though.

**Comment by Sleet01** [comment] 2018-05-08 23:49
This new fix has broader reach and avoids some exception-throwing paths that the earlier, more focused fix might have run into.  This should go into the next bug fix PR, and hopefully into release in a few weeks.

**Comment by Sleet01** [comment] 2018-05-23 05:15
This fix is now in Release; closing.

**Closed as completed by Sleet01** 2018-05-23 05:15 UTC
