### ISSUE TITLE
Docked attack shuttle automatically undocking

### ISSUE THREAD

**Issue by AntipodeanOrk** [baranidlo/bench#49] opened 2018-02-07 22:59 UTC
Every time with the AI, and recently while testing the current meta-storming Ghost/Attack Shuttle and Fenn shuttle even in "player" mode, the docked attack shuttle is undocking on the first activation.

**Comment by Sleet01** [comment] 2018-02-08 01:02
I can take a look, but there are some changes to docking and deploying in the pipe already, so we may have to wait until the next revision is released before digging into this very deeply.

**Comment by AntipodeanOrk** [comment] 2018-02-11 05:26
Thanks. I realised, if it helps, that it only happens when the docked
shuttle is "player two" - regardless of whether computer or player control
is set

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Sleet01** [comment] 2018-02-11 22:03
Okay, that narrowed it down!

Currently there is no code to determine if it is a good time for a ship to deploy any of its docked ships.  The AI is provided with the "Ghost" action prompt, and, having no way to determine if that is a good choice, it automatically activates that action.

I've added a very basic method for the AI to see if an action prompt has an attached judgement function and, if so, to use the provided function to choose whether or not to use a given action.  Currently this is only on the Ghost card but it could be used for e.g. more intelligent Vader activation, or the Gozanti (if it is ever implemented).

**Comment by TNG-Wing** [comment] 2018-02-12 21:04
BTW, I see this issue also when flying the Ghost/Shuttle as a human player. 

Maybe you can:

1) Model this after the Palpatine option. Leave the AI choice to deploy with the human player. I know it's kind of strange, but so is giving Palpatine's AI power choice to the human player. It's better than auto undocking, no?

2) Have it autodeploy when the Ghost is destroyed (I've seen this on https://xws-bench.github.io/bench/)

Or,

3) Make it that when the Ghost is down to 2 health it will trigger the option to undock. 

I think option 1 or 3 is best, and include option 2 anyway. 
:)

Thanks for all the amazing work!!

**Comment by Sleet01** [comment] 2018-02-12 23:46
I haven't seen the player's Phantom undock before, but again, I'm testing on more recent code so this may no longer be an issue in test.  I will see if I can confirm that this is also fixed.

**Comment by TNG-Wing** [comment] 2018-02-12 23:50
I just tested it with Kanan, Ezra (attack shuttle docked), and Fenn Rau (Stealthidpede) and it undocked right after the first action

thanks

**Comment by TNG-Wing** [comment] 2018-02-13 00:43
To clarify, this was the Original Attack Shuttle that unlocks right after the first activation phase,  both as AI and Human player.  Again,  this happens on https://github.com/baranidlo/bench

**Comment by TNG-Wing** [comment] 2018-02-13 00:44
Correction: it happens on https://baranidlo.github.io/bench/

**Comment by Sleet01** [comment] 2018-02-13 01:44
We must be using different lists.  Please post both exact lists (player and computer) from the game which gives you the 100% repro and I'll see what I can do.  Thanks!

**Comment by TNG-Wing** [comment] 2018-02-13 07:24
Zeb Orrelios(Attack Shuttle) + Chopper + Phantom
Lowhhrick + Trick Shot + Jan Ors
Kanan Jarrus + Accuracy Corrector + Twin Laser Turret + Rey + Recon Specialist + Ghost

However, I just realized that it was always using Player 2 (Human/AI)

I will try this list as player 1

But it would be great to see this fixed.  Thanks!!!

**Comment by TNG-Wing** [comment] 2018-02-13 07:32
As Player 1 (AI) the auto undock still happens. As Player 1 (Human) it doesn't undock. It gives you the ability to chose/skip undocking.

**Comment by Sleet01** [comment] 2018-02-13 07:40
Okay, just to summarize: the above list always deploys the Phantom, but so far you've only seen this when the AI was running it?

That's a known issue, and that functionality is fixed in the next Pull Request (so probably a few weeks out from release).  The new code deploys the Phantom or Phantom II if the Ghost drops below 5 hull and shields combined, but it can be adjusted fairly simply - and we now have a mechanism for implementing fairly robust AI on specific upgrade cards if it looks like it needs more nuance.

Please do update if you see this happening with the human player.  For the AI stuff, I understand it's frustrating but I hope the updated version will be worth the wait.  And thanks for all the testing help!

**Comment by TNG-Wing** [comment] 2018-02-13 07:42
Thank YOU for letting me give feedback! I hope you don't mind if I find other issues and bring them to your attention. I don't take any of it for granted and appreciate all you've done to make this game possible!

**Comment by Sleet01** [comment] 2018-05-02 16:26
This should be working properly now.  Please don't hesitate to file new bugs as you encounter them!

**Closed as completed by Sleet01** 2018-05-02 16:26 UTC
