### ISSUE TITLE
r4-d6 randomly adds/multiplies the amount of stress on its ship.

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#8] opened 2017-12-28 04:01 UTC
This is one of the more bizarre bugs i encountered on all versions of squadron benchmark.

As an example of one the times this occurs, a biggs with r4-d6 attacks another biggs with r4-d6.

attacking biggs rolls 1 hit. defending biggs rolls 3 evades (its range 3). The attacking biggs receives 16 stress. I have seen this end in thousands of stress after a couple of turns on a couple occasions

**Comment by Sleet01** [comment] 2018-01-15 20:08
I recently checked in a fix for R4-D6 stress spam, but I haven't tested it with two opposing Biggs pilots.  Let me see if this has dropped out or if there is a more fundamental issue in the code that determines which pilot is active / affected by a card.  If I had to guess, there may be an issue separating identical cards/ships by team during the modification application steps.

**Comment by Sleet01** [comment] 2018-01-15 20:52
Okay, the issue isn't that there's a fundamental problem telling which ship is activating, but that we're not using those checks in a lot of cases where an ability on an AI ship might be automatically applied to its target instead of itself, due to the way that dice modifications are checked and applied.

Long story short, the stress spam issue has been fixed on the Devel branch already, but I needed to add an additional check to prevent an AI R4-D6 ship from using its own ability to cancel dice on its own attack against a player's R4-D6 ship.

**Comment by Sleet01** [comment] 2018-05-01 16:28
This has been fixed for a while; closing.

**Closed as completed by Sleet01** 2018-05-01 16:28 UTC
